### ISSUE TITLE
[SUGGESTION] AME Playbook

### ISSUE THREAD

**Issue by MarcoRavich** [heitorrosa/FemboyOS#1]
Hi there, just discovered this interesting - and almost unique - project.

As many other [Windows-customs](https://github.com/MarcoRavich/Opendows#open-source-customized-windows-isos) have already done, I strongly suggest to release an [Playbook](https://docs.ameliorated.io/playbooks.html) version trough [AME Wizard](https://ameliorated.io/) too.

Hope that inspires !

**Comment by heitorrosa** [comment]
I had the idea of porting it to AME-Wizard but decided to make it flashable to any system with a batch script, AME's back end is closed source and cannot be trusted, batch files are fully customizable in the other hand, if AME's disclousure their back-end, ill prob move the files there

**Comment by MarcoRavich** [comment]
Thanks for reply, check out my (linked above) repo anyway.
